name: Branding Brand
favicon: null
layout_spectrum: 0.7179701824206859
typography_spectrum: 0.34389046858996153
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05335781769827008
  lightness: 0.8640796635299921
  saturation: 0.2519850314129144
  rhythmicContrast: 0.7380226547829807
purpose: []
